---
- name: Install Apache and Git, clone repository, and configure web server
  hosts: uat-webservers
  become: true
  tasks:
    - name: Install Apache
      ansible.builtin.yum:
        name: "httpd"
        state: present

    - name: Install Git
      ansible.builtin.yum:
        name: "git"
        state: present

    - name: Clone a repo
      ansible.builtin.git:
        repo: https://github.com/sukieoduwole/tooling.git
        dest: /var/www/html
        force: yes

    - name: Copy HTML content to one level up
      command: cp -r /var/www/html/html/ /var/www/
      become: true

    - name: Start Apache service if not started
      ansible.builtin.service:
        name: httpd
        state: started
      become: true

    - name: Recursively remove /var/www/html/html/ directory
      ansible.builtin.file:
        path: /var/www/html/html
        state: absent
      become: true